- name: Get kubeconfig
  block:
    - name: Download the kubeconfig
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /tmp/kubeconfig-k3s
        flat: yes
      changed_when: false

    - name: Set correct host
      replace:
        path: /tmp/kubeconfig-k3s
        regexp: '127.0.0.1'
        replace: "{{ansible_default_ipv4['address']}}"
      delegate_to: localhost
      changed_when: false
